//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res_man_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int mahoadon { get; set; }
        public int mamonan { get; set; }
        public string tenmonan { get; set; }
        public Nullable<double> giamonan { get; set; }
        public Nullable<decimal> soluong { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
