//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res_man_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATBAN
    {
        public int madatban { get; set; }
        public Nullable<int> mamonan { get; set; }
        public Nullable<int> maban { get; set; }
        public string khuvuc { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
