//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res_man_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public int makh { get; set; }
        public Nullable<int> matin { get; set; }
        public Nullable<int> matk { get; set; }
        public string hoten { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public Nullable<decimal> dienthoai { get; set; }
        public Nullable<int> madatban { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TINTUC TINTUC { get; set; }
        public virtual DATBAN DATBAN { get; set; }
    }
}
