//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res_man_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string manv { get; set; }
        public Nullable<int> matk { get; set; }
        public string tennv { get; set; }
        public string Chucvu { get; set; }
        public string calam { get; set; }
        public string khuvuc { get; set; }
        public string diachi { get; set; }
        public Nullable<decimal> sodienthoai { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
